name: alpaca_auto_trading_app
description: A Flutter application for automated trading using Alpaca and ChatGPT.
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  provider: ^5.0.0
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/