apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning
  namespace: alpaca-iq
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Tempo
        type: tempo
        access: proxy
        url: http://tempo.alpaca-iq.svc.cluster.local:3200
        isDefault: true
      - name: Loki
        type: loki
        access: proxy
        url: http://loki.alpaca-iq.svc.cluster.local:3100