apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning
  namespace: alpaca-iq
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Tempo
        type: tempo
        access: proxy
        url: http://tempo.alpaca-iq.svc.cluster.local:3200
        isDefault: true
  dashboards.yaml: |
    apiVersion: 1
    providers:
      - name: 'Alpaca IQ'
        folder: 'Alpaca IQ'
        type: file
        options:
          path: /var/lib/grafana/dashboards
